use_frameworks!

platform :ios, '10.0'

target 'StickyFooterScrollView_Example' do
  pod 'StickyFooterScrollView', :path => '../'

  target 'StickyFooterScrollView_Tests' do
    inherit! :search_paths

    
  end
end
